name: DigiCert Code Scan

on:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: Java
            build-mode: none
          - language: JavaScript
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
          upload: false
          output: "codeql-${{ matrix.language }}.sarif"

      - name: Upload SARIF result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-${{ matrix.language }}
          path: codeql-${{ matrix.language }}.sarif

  zip-sarif:
    name: Zip All SARIF Results
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Download all SARIF artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: codeql-sarif-*
          path: ./sarif-results

      - name: Zip SARIF results
        run: |
          cd sarif-results
          zip ../codeql-sarif-results.zip *.sarif

      - name: Upload zipped SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-results
          path: codeql-sarif-results.zip
